# Generated by Django 5.0.1 on 2024-05-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_name_alter_movie_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['name'], name='movies_movi_name_98114c_idx'),
        ),
    ]
