# Generated by Django 5.0.1 on 2024-09-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_movies_movi_name_98114c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
