# Generated by Django 5.0.1 on 2024-09-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_user_usersearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_use',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
