# Generated by Django 5.0.1 on 2024-09-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_user_last_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
