# Generated by Django 5.0.1 on 2024-09-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_link_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subtitle_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
