# Generated by Django 5.0.1 on 2024-09-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_subtitle_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
